export const teams = [
  "Bangladesh",
  "Australia",
  "England",
  "Newzealand",
  "Pakistan",
  "India",
  
];

export const players = {
 "Bangladesh": [
  {
    id: 1,
    name: "Tamim Iqbal",
    role: "Batsman",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 2,
    name: "Liton Das",
    role: "Wicketkeeper-Batsman",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 3,
    name: "Shakib Al Hasan",
    role: "All-Rounder",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 4,
    name: "Mushfiqur Rahim",
    role: "Wicketkeeper-Batsman",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 5,
    name: "Mahmudullah",
    role: "All-Rounder",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 6,
    name: "Mohammad Mithun",
    role: "Wicketkeeper-Batsman",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 7,
    name: "Mosaddek Hossain",
    role: "All-Rounder",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 8,
    name: "Afif Hossain",
    role: "All-Rounder",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 9,
    name: "Taskin Ahmed",
    role: "Bowler",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 10,
    name: "Mehidy Hasan",
    role: "Bowler",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
  {
    id: 11,
    name: "Mustafizur Rahman",
    role: "Bowler",
    country: "Bangladesh",
    wickets: 0,
    runs: 0,
    overs: 0,
  },
    // You can add more players if needed
  ],

  "Australia": [
    {
      id: 12,
      name: "David Warner",
      role: "Batsman",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 13,
      name: "Aaron Finch",
      role: "Batsman",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 14,
      name: "Steve Smith",
      role: "Batsman",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 15,
      name: "Glenn Maxwell",
      role: "All-Rounder",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 16,
      name: "Mitchell Marsh",
      role: "All-Rounder",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 17,
      name: "Alex Carey",
      role: "Wicketkeeper-Batsman",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 18,
      name: "Pat Cummins",
      role: "Bowler",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 19,
      name: "Mitchell Starc",
      role: "Bowler",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 20,
      name: "Adam Zampa",
      role: "Bowler",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 21,
      name: "Josh Hazlewood",
      role: "Bowler",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 22,
      name: "Marcus Stoinis",
      role: "All-Rounder",
      country: "Australia",
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    // You can add more players if needed
  ],

  "Afghanistan": [
    {
      id: 23,
      name: 'Rahmat Shah',
      role: 'Batsman',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 24,
      name: 'Hashmatullah Shahidi',
      role: 'Batsman',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 25,
      name: 'Asghar Afghan',
      role: 'Batsman',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 26,
      name: 'Mohammad Nabi',
      role: 'All-Rounder',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 27,
      name: 'Rashid Khan',
      role: 'Bowler',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 28,
      name: 'Mujeeb Ur Rahman',
      role: 'Bowler',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 29,
      name: 'Najibullah Zadran',
      role: 'Batsman',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 30,
      name: 'Gulbadin Naib',
      role: 'All-Rounder',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 31,
      name: 'Ikram Alikhil',
      role: 'Wicketkeeper-Batsman',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 32,
      name: 'Karim Janat',
      role: 'All-Rounder',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 33,
      name: 'Hamid Hassan',
      role: 'Bowler',
      country: 'Afghanistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
  ],

  
  "England": [
    {
      id: 34,
      name: 'Joe Root',
      role: 'Batsman',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 35,
      name: 'Jason Roy',
      role: 'Batsman',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 36,
      name: 'Jos Buttler',
      role: 'Wicketkeeper-Batsman',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 37,
      name: 'Ben Stokes',
      role: 'All-Rounder',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 38,
      name: 'Eoin Morgan',
      role: 'Batsman',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 39,
      name: 'Jonny Bairstow',
      role: 'Wicketkeeper-Batsman',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 40,
      name: 'Chris Woakes',
      role: 'All-Rounder',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 41,
      name: 'Jofra Archer',
      role: 'Bowler',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 42,
      name: 'Adil Rashid',
      role: 'Bowler',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 43,
      name: 'Mark Wood',
      role: 'Bowler',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 44,
      name: 'Moeen Ali',
      role: 'All-Rounder',
      country: 'England',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
  ],

  "Pakistan": [
    {
      id: 45,
      name: 'Fakhar Zaman',
      role: 'Batsman',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 46,
      name: 'Babar Azam',
      role: 'Batsman',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 47,
      name: 'Mohammad Rizwan',
      role: 'Wicketkeeper-Batsman',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 48,
      name: 'Shoaib Malik',
      role: 'All-Rounder',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 49,
      name: 'Imad Wasim',
      role: 'All-Rounder',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 50,
      name: 'Sarfaraz Ahmed',
      role: 'Wicketkeeper-Batsman',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 51,
      name: 'Shadab Khan',
      role: 'All-Rounder',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 52,
      name: 'Hasan Ali',
      role: 'Bowler',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 53,
      name: 'Shaheen Afridi',
      role: 'Bowler',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 54,
      name: 'Haris Rauf',
      role: 'Bowler',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 55,
      name: 'Fahim Ashraf',
      role: 'All-Rounder',
      country: 'Pakistan',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
  ],

  "India": [
    {
      id: 56,
      name: 'Shikhar Dhawan',
      role: 'Batsman',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 57,
      name: 'Rohit Sharma',
      role: 'Batsman',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 58,
      name: 'Virat Kohli',
      role: 'Batsman',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 59,
      name: 'KL Rahul',
      role: 'Wicketkeeper-Batsman',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 60,
      name: 'Rishabh Pant',
      role: 'Wicketkeeper-Batsman',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 61,
      name: 'Hardik Pandya',
      role: 'All-Rounder',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 62,
      name: 'Washington Sundar',
      role: 'All-Rounder',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 63,
      name: 'Jasprit Bumrah',
      role: 'Bowler',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 64,
      name: 'Mohammed Shami',
      role: 'Bowler',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 65,
      name: 'Yuzvendra Chahal',
      role: 'Bowler',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    {
      id: 66,
      name: 'Ravindra Jadeja',
      role: 'All-Rounder',
      country: 'India',
      wickets: 0,
      runs: 0,
      overs: 0,
    },
    
  ],

};
